# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
language: objective-c

cache: 
- cocoapods
- xcpretty
podfile: Example/Podfile
rvm:
- 2.2.2
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- gem install xcpretty
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/UVCardView.xcworkspace -scheme UVCardView-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
